### ISSUE TITLE
Suggestion: SQL Server specific attributes

### ISSUE THREAD

**Issue by danspark** [VerifyTests/Verify.SqlServer#573]
#### Is the feature request related to a problem

Not a problem, just an increment.

#### Describe the solution

Since this package is SQL Server specific, would be nice to see SQL Server specific fields such as `SqlParameter.SqlDbType`. Additionally, could be nice to also add other `DbParameter` attributes, such as `Size`, `Precision` and/or `Scale`. Personally, the `SqlDbType` would help me notice if a command is using NVarchar instead of Varchar. This is achievable through the `DbType` `AnsiString`/String`, but I think it still would be useful to have it, maybe by having fields being serialized by default instead of hand-picking them?

#### Describe alternatives considered

Looking at the source, looks like it can be achieved by implementing my own diagnostic listener and grabbing the fields I want. Also `DbCommand.DbType` kind of gives me this information.

#### Additional context

I decided to open an issue instead of a pull request just to hear your thoughts on it.

**Comment by SimonCropp** [comment]
what api are you referring to here?

**Comment by SimonCropp** [comment]
in that case. yep i am happy to accept a PR

**Comment by SimonCropp** [comment]
can u try 9.0.0-beta.1
