### ISSUE TITLE
[Suggestion] Allowing filtering based on schema

### ISSUE THREAD

**Issue by BraedonWooding** [VerifyTests/Verify.SqlServer#588]
#### Is the feature request related to a problem

Currently, we run our tests in 2 modes; with one of them being a shared database where the schemas are postfixed with a guid to avoid collision.

One of the tests we run is to verify the schema hasn't changed i.e. we run a Verify(sqlConnection).  This, however, runs across the entire database.  I was going to use `SchemaSettings(includeItem: (x)` but x is the table name :( which is the same for us (only schema is different) so we can't filter them out.

#### Describe the solution

I'm happy to create a PR to fix this but not sure what the best API approach is here, I'm thinking we change the https://github.com/VerifyTests/Verify.SqlServer/blob/main/src/Verify.SqlServer/SchemaValidation/SchemaSettings.cs file to something like this;
```cs
// New constructor
﻿class SchemaSettings(
    bool storedProcedures,
    bool tables,
    bool views,
    bool userDefinedFunctions,
    bool synonyms,
    Func<NamedSmoObject, bool> includeItem)
{
    public bool StoredProcedures { get; } = storedProcedures;
    public bool Tables { get; } = tables;
    public bool Views { get; } = views;
    public bool Synonyms { get; } = synonyms;
    public bool UserDefinedFunctions { get; } = userDefinedFunctions;
    public Func<NamedSmoObject, bool> IncludeItem { get; } = includeItem;

    SchemaSettings(
      bool storedProcedures,
      bool tables,
      bool views,
      bool userDefinedFunctions,
      bool synonyms,
      Func<string, bool> includeItem) : this(storedProcedures, tables, views, userDefinedFunctions, synonyms, 
 // putting on new line to make clear, this just maps it to the "new" function
 ((item) => includeItem(item.Name))) {}
}
```

Then in my case I can just do a type-cast check on NamedSmoObject to either Table/View/others and extract schema that way.

This should be pretty transparent to the user and won't break any existing code.

#### Describe alternatives considered

I'm not too sure but open to alternatives.

#### Additional context

None I can think of.

**Comment by SimonCropp** [comment]
@BraedonWooding your suggestion looks like a good way to go. And i am happy to accept a PR that makes the change

**Comment by SimonCropp** [comment]
can u try 9.0.0-beta.1
